# swaggerバージョン宣言
openapi: 3.0.0

info:
  title: Facility-Reservation-api
  description: 施設予約API
#  termsOfService: http://example.com/terms/
#  contact:
#    name: API support
#    url: http://www.example.com/support
#    email: support@example.com
#  license:
#    name: Apache 2.0
#    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
  - url: https://dev.xxxxxxxxxxxxx.com/v1
    description: Development server
  - url: https://stg.xxxxxxxxxxxxx.com/v1
    description: Staging server
  - url: https://api.xxxxxxxxxxxxx.com/v1
    description: Production server

paths:
  # paths オブジェクト
  /facilities:
    # path item オブジェクト
    get: # GET
      # Operationオブジェクト
      tags:
        - facilities
      summary: Get all users.
      description: Returns an array of Facility model
      parameters: []
      responses: # レスポンス定義
        '200': # HTTP status
          description: A JSON array of Facility model
          content:
            application/json: # レスポンスの形式指定
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Facility' # 参照するモデル
                example: # サンプルデータ
                  - id: 1
                    name: A施設
                  - id: 2
                    name: B施設
    post: # POST
      tags: 
        - facilities
      summary: Create a new Facility
      description: Create a new Facility
      parameters: []
      requestBody: # リクエストボディ
        description: Facility to create
        content:
          application/json:
            schema: # POSTするオブジェクト
              $ref: '#/components/schemas/Facility'
            example:
              id: 3
              name: C施設
      responses:
        '201':
          description: CREATED
  /facilities/{facilityId}:
    get:
      tags:
        - facilities
      summary: Get Facility by ID.
      description: Returns a single Facility model
      parameters: # リクエストパラメータ
        - name: facilityId
          in: path # パラメータをパス内に含める
          description: facility id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single Facility model
          content:
            application/json:
              schema: 
                type: object
                items:
                  $ref: '#/components/schemas/Facility'
                example:
                  id: 1
                  name: A施設
components:
  schemas: # スキーマオブジェクトの定義
    Facility: # モデル名
      type: object # 型
      required: # 必須フィールド
        - id
      properties:
        id: # プロパティ名
          type: integer # 型 
          format: int64 # フォーマット(int32, int64等)
        facilityName:
          type: string
    Product:
      type: object
      required:
        - id
        - price
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Laptop
        price:
          type: integer
          example: 1200